name: Pytest

on:
  push:
    branches: [ "master", "change_get_user_by_email" ]
  pull_request:
    branches: [ "master", "change_get_user_by_email" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_DATABASE: rootDb
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
        options: >-
          --name edutask-mongodb
          --health-cmd "mongosh --username root --password root --authenticationDatabase admin --eval 'db.adminCommand({ ping: 1 })'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
        command: [ "mongod", "--bind_ip_all" ]

    env:
      MONGO_URL: mongodb://root:root@localhost:27017/rootDb

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./backend/requirements.pip

      - name: Unit Tests
        working-directory: ./backend
        run: |
          python -m pytest -m unit

      - name: Integration Tests
        working-directory: ./backend
        run: |
          python -m pytest -m integration
